FROM node:18-alpine

WORKDIR /app

# Copy only package files first
COPY package*.json ./

# Install production dependencies
RUN npm ci --omit=dev
RUN npm install -g pm2

# Copy source code
COPY . .

EXPOSE 3000

CMD ["pm2-runtime", "src/server.js"]
