
# #  Production build (commented out)
FROM node:24 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

FROM node:18-alpine

WORKDIR /app
COPY --from=build /app .

RUN npm prune --production

EXPOSE 3000
CMD ["node", "src/server.js"]
