# Use root/example as user/password credentials
# run : docker-compose -f database/example_mysql_compose.yml up -d
services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    # (this is just an example, not intended to be a production configuration)

