version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Strong!Pass123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "14330:1433"   # 14330 trên host → 1433 container
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
# To run: docker-compose -f database/sqlserver_compose.yml up -d